import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, BarChart3, Camera, CheckCircle2, ChevronRight, CloudRain, Cpu, Droplets, Gauge, Leaf, Menu, RefreshCw, Settings as SettingsIcon, ShieldCheck, Sprout, Thermometer, Upload, Waves, X } from 'lucide-react';
import { crops, demoReading, demoWeather, Page, Mode, Reading, trend, validateReading } from './data';

const nav: { label: Page; icon: typeof Leaf }[] = [
  { label: 'Dashboard', icon: BarChart3 }, { label: 'Crop Advisory', icon: Sprout }, { label: 'Disease Detection', icon: Camera },
  { label: 'Soil Analysis', icon: Droplets }, { label: 'Sensor Monitoring', icon: Activity }, { label: 'Recommendations', icon: CheckCircle2 }, { label: 'Settings', icon: SettingsIcon },
];
const pageCopy: Record<Page, { eyebrow: string; title: string; description: string }> = {
  Dashboard: { eyebrow: 'Overview', title: 'Field intelligence at a glance', description: 'Understand current soil and environmental conditions before making your next crop decision.' },
  'Crop Advisory': { eyebrow: 'Decision support', title: 'Find the best crop fit', description: 'A transparent prototype scoring model based on the current conditions—not a scientifically validated prediction.' },
  'Disease Detection': { eyebrow: 'ESP32-CAM pathway', title: 'Inspect a crop leaf', description: 'Upload a leaf image to view a clearly labeled demonstration result.' },
  'Soil Analysis': { eyebrow: 'Soil health', title: 'Read the soil story', description: 'Simple status indicators explain what the current prototype readings mean.' },
  'Sensor Monitoring': { eyebrow: 'Hardware bridge', title: 'Monitor live telemetry', description: 'See the path from sensors to ESP32 to the web dashboard.' },
  Recommendations: { eyebrow: 'Action plan', title: 'Practical next steps', description: 'General, safe guidance built from soil condition, crop suitability, and the demo disease result.' },
  Settings: { eyebrow: 'System controls', title: 'Configure the prototype', description: 'Choose how this academic project should source and label its readings.' },
};

function Badge({ mode, small = false }: { mode: Mode; small?: boolean }) { return <span className={`badge ${mode === 'demo' ? 'badge-demo' : 'badge-live'} ${small ? 'small' : ''}`}><span className="dot" />{mode === 'demo' ? 'DEMO DATA' : 'LIVE HARDWARE'}</span>; }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section>; }
function SectionTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { return <div className="section-title"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>; }
function StatCard({ label, value, unit, icon: Icon, tone, note }: { label: string; value: string | number; unit?: string; icon: typeof Leaf; tone: string; note: string }) { return <Card className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={20} /></div><div className="stat-copy"><span>{label}</span><strong>{value}<em>{unit}</em></strong><small>{note}</small></div></Card>; }

function Dashboard({ reading, mode, setPage }: { reading: Reading; mode: Mode; setPage: (p: Page) => void }) {
  return <>
    <div className="hero-grid"><Card className="welcome"><div className="hero-leaf"><Leaf size={28} /></div><div><span className="overline">FIELD SNAPSHOT</span><h2>Good morning, farmer</h2><p>Your current conditions are ready for a simple, explainable crop decision.</p><button className="button primary" onClick={() => setPage('Crop Advisory')}>Open crop advisory <ChevronRight size={16} /></button></div></Card><Card className="weather"><div className="weather-top"><div><span className="overline">DEMONSTRATION WEATHER</span><h3>{demoWeather.location}</h3></div><CloudRain size={26} /></div><div className="weather-main"><strong>{demoWeather.temperature}°</strong><div><b>{demoWeather.condition}</b><span>Humidity {demoWeather.humidity}% · Rainfall {demoWeather.rainfall} mm</span></div></div><p className="fine-print">Not real-time weather data</p></Card></div>
    <div className="stats-grid"><StatCard label="Soil moisture" value={reading.soilMoisture} unit="%" icon={Droplets} tone="teal" note="Normal range" /><StatCard label="Soil pH" value={reading.soilPH} icon={Gauge} tone="violet" note="Suitable range" /><StatCard label="Temperature" value={reading.temperature} unit="°C" icon={Thermometer} tone="orange" note="Environmental" /><StatCard label="Humidity" value={reading.humidity} unit="%" icon={Waves} tone="blue" note="Moderate" /></div>
    <div className="two-col"><Card><SectionTitle title="Crop suitability" subtitle="Prototype suitability score" action={<button className="text-button" onClick={() => setPage('Crop Advisory')}>View details <ChevronRight size={15} /></button>} /><div className="crop-list">{crops.map((crop) => <div className="crop-row" key={crop.name}><div className="crop-name"><span className={`crop-mark ${crop.tone}`}><Sprout size={16} /></span><b>{crop.name}</b></div><div className="progress"><span style={{ width: `${crop.score}%` }} /></div><strong>{crop.score}%</strong></div>)}</div><div className="notice"><AlertTriangle size={16} /><span>Scores are a transparent prototype model and are not scientifically validated.</span></div></Card><Card><SectionTitle title="Recent sensor trend" subtitle="Last five demonstration readings" action={<button className="text-button" onClick={() => setPage('Sensor Monitoring')}>Open monitor <ChevronRight size={15} /></button>} /><div className="chart-wrap"><ResponsiveContainer width="100%" height={200}><AreaChart data={trend}><defs><linearGradient id="moisture" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2d8c61" stopOpacity={0.24}/><stop offset="100%" stopColor="#2d8c61" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7eee9"/><XAxis dataKey="time" tickLine={false} axisLine={false} tick={{fontSize:11, fill:'#819187'}}/><YAxis tickLine={false} axisLine={false} tick={{fontSize:11, fill:'#819187'}} width={30}/><Tooltip/><Area type="monotone" dataKey="moisture" stroke="#2d8c61" fill="url(#moisture)" strokeWidth={2} name="Moisture %"/></AreaChart></ResponsiveContainer></div></Card></div>
    <Card><SectionTitle title="Recommendation summary" subtitle="Based on current prototype conditions" /><div className="recommendation"><div className="rec-icon"><ShieldCheck size={24}/></div><div><h3>Groundnut shows good suitability</h3><p>Maintain moderate soil moisture, continue observing plant health, and use the soil analysis page before making changes.</p></div><button className="button ghost" onClick={() => setPage('Recommendations')}>See recommendations <ChevronRight size={15}/></button></div></Card>
  </>;
}

function Advisory({ reading }: { reading: Reading }) { return <><Card className="method-card"><div className="method-icon"><Sprout size={23}/></div><div><h3>Prototype weighted scoring</h3><p>Scores combine soil pH, soil moisture, temperature, humidity, and demonstration rainfall.</p></div><div className="weight-list"><span>pH <b>30%</b></span><span>Moisture <b>25%</b></span><span>Temperature <b>20%</b></span><span>Humidity <b>10%</b></span><span>Rainfall <b>15%</b></span></div></Card><Card><SectionTitle title="Recommended crops" subtitle={`Using pH ${reading.soilPH}, moisture ${reading.soilMoisture}%, temperature ${reading.temperature}°C, humidity ${reading.humidity}%`} /><div className="advisory-grid">{crops.map((crop, index) => <div className="advisory-card" key={crop.name}><div className="rank">0{index + 1}</div><Sprout size={22} className="green-icon"/><h3>{crop.name}</h3><div className="score-big">{crop.score}<small>%</small></div><div className="progress"><span style={{width:`${crop.score}%`}}/></div><p>{index === 0 ? 'Strong fit under current prototype conditions.' : index === 1 ? 'Good fit with regular moisture monitoring.' : 'Possible fit; review local agronomic context.'}</p></div>)}</div><div className="notice"><AlertTriangle size={16}/><span>Prototype suitability score only. This is not a scientifically validated prediction or a replacement for professional agricultural advice.</span></div></Card></>; }

function Disease() { const [image, setImage] = useState<string | null>(null); return <div className="two-col disease-layout"><Card><SectionTitle title="Upload crop leaf image" subtitle="Prototype Disease Detection" /><label className="upload-box">{image ? <img src={image} alt="Uploaded crop leaf preview" /> : <><div className="upload-icon"><Upload size={22}/></div><b>Choose a crop leaf image</b><span>PNG, JPG, or WEBP · ESP32-CAM compatible workflow</span></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => { const file = e.target.files?.[0]; if (file) setImage(URL.createObjectURL(file)); }} /></label>{!image && <div className="inline-warning"><AlertTriangle size={16}/>Please upload a crop leaf image to replace the demonstration result.</div>}</Card><Card><SectionTitle title="Demonstration result" subtitle="Clearly labeled example output" /><div className="disease-result"><div className="result-top"><div className="result-status"><span className="status-dot"/>Demo result</div><span className="severity">Moderate</span></div><h2>Tomato Early Blight</h2><div className="confidence"><span>Confidence</span><strong>92%</strong></div><ul><li>Brown circular lesions</li><li>Yellowing of leaves</li><li>Lower leaves affected</li><li>Concentric ring patterns</li></ul><div className="safe-note"><ShieldCheck size={17}/><span>General guidance only. No pesticide dosage instructions are provided.</span></div></div></Card><Card className="path-card"><SectionTitle title="ESP32-CAM pathway"/><div className="flow"><span>Crop leaf</span><ChevronRight/><span>ESP32-CAM</span><ChevronRight/><span>Leaf image</span><ChevronRight/><span>Prototype result</span></div></Card></div>; }

function Soil({ reading }: { reading: Reading }) { const moistureGood = reading.soilMoisture >= 30 && reading.soilMoisture <= 70; const phGood = reading.soilPH >= 6 && reading.soilPH <= 7.5; return <><div className="soil-score-grid"><Card className="soil-score"><div className="ring" style={{'--value': `${reading.soilMoisture * 3.6}deg`} as React.CSSProperties}><div><strong>{reading.soilMoisture}%</strong><span>Moisture</span></div></div><div><h3>Soil moisture</h3><span className="status-pill good">{moistureGood ? 'Normal' : 'Review'}</span><p>{moistureGood ? 'Moisture is within the prototype reference range.' : 'Check the physical sensor and local field conditions.'}</p></div></Card><Card className="soil-score"><div className="ph-display"><strong>{reading.soilPH}</strong><span>pH</span></div><div><h3>Soil pH</h3><span className={`status-pill ${phGood ? 'good' : 'warn'}`}>{phGood ? 'Suitable' : 'Review'}</span><p>{phGood ? 'The reading is within a broad reference range.' : 'Calibrate the pH sensor before relying on this value.'}</p></div></Card></div><Card><SectionTitle title="Current soil conditions" subtitle="Explainable status indicators"/><div className="condition-table"><div><span>Moisture level</span><b>{reading.soilMoisture}%</b><em className="good-text">Normal</em></div><div><span>pH level</span><b>{reading.soilPH}</b><em className="good-text">Suitable</em></div><div><span>Calibration note</span><b>Required</b><em className="warn-text">Sensor-specific</em></div></div><div className="notice"><AlertTriangle size={16}/><span>FC-28 is a low-cost resistive prototype sensor, not precision agricultural instrumentation. pH values require suitable buffer calibration and ADC safety checks.</span></div></Card><Card><SectionTitle title="Historical readings" subtitle="Demonstration trend"/><div className="chart-wrap tall"><ResponsiveContainer width="100%" height={240}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7eee9"/><XAxis dataKey="time" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Line type="monotone" dataKey="moisture" stroke="#218b67" strokeWidth={2} dot={false} name="Moisture %"/><Line type="monotone" dataKey="ph" stroke="#7c65c1" strokeWidth={2} dot={false} name="pH"/></LineChart></ResponsiveContainer></div></Card></>; }

function Sensors({ mode, reading }: { mode: Mode; reading: Reading }) { const live = mode === 'live'; const telemetry: [string, string | number, typeof Droplets][] = [['Soil Moisture', `${reading.soilMoisture}%`, Droplets], ['Soil pH', reading.soilPH, Gauge], ['Temperature', `${reading.temperature}°C`, Thermometer], ['Humidity', `${reading.humidity}%`, Waves]]; return <><Card><div className="sensor-head"><div><SectionTitle title="Live telemetry" subtitle="Data source status is always explicit"/></div><Badge mode={mode}/></div><div className="telemetry-grid">{telemetry.map(([label, value, Icon]) => <div className="telemetry" key={String(label)}><Icon size={18}/><span>{label}</span><strong>{value as string}</strong></div>)}</div>{live ? <div className="hardware-alert danger"><AlertTriangle size={18}/><div><b>Hardware unavailable</b><span>No verified ESP32 telemetry has been received yet. Demo values are not shown in Live Hardware mode.</span></div></div> : <div className="hardware-alert"><CheckCircle2 size={18}/><div><b>Demo readings active</b><span>These centralized prototype values are labeled DEMO DATA and are not real sensor measurements.</span></div></div>}</Card><Card><SectionTitle title="Sensor trends" subtitle="Moisture, temperature, humidity, and pH over time"/><div className="chart-wrap tall"><ResponsiveContainer width="100%" height={270}><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7eee9"/><XAxis dataKey="time" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Line type="monotone" dataKey="moisture" stroke="#218b67" strokeWidth={2} dot={false} name="Moisture %"/><Line type="monotone" dataKey="temperature" stroke="#e39b4e" strokeWidth={2} dot={false} name="Temperature °C"/><Line type="monotone" dataKey="humidity" stroke="#4c86c6" strokeWidth={2} dot={false} name="Humidity %"/><Line type="monotone" dataKey="ph" stroke="#8063ba" strokeWidth={2} dot={false} name="pH"/></LineChart></ResponsiveContainer></div></Card><div className="two-col"><Card><SectionTitle title="How it works"/><div className="vertical-flow">{['Sensor','ESP32','Calibration','Validation','Wi-Fi + HTTP/JSON','Backend','Web dashboard'].map((step, i) => <div key={step}><span>{i + 1}</span><b>{step}</b>{i < 6 && <div className="flow-line"/>}</div>)}</div></Card><Card><SectionTitle title="Wiring & pinout" subtitle="Verify hardware-specific voltage requirements before connecting."/><div className="pinout"><div><b>FC-28</b><span>A0 → GPIO 34</span></div><div><b>Soil pH</b><span>Analog → GPIO 35</span></div><div><b>DHT11</b><span>DATA → GPIO 4</span></div></div><pre>{`// Telemetry shape sent by ESP32\nPOST /api/hardware/telemetry\n{\n  soilMoisture: 42, soilPH: 6.8,\n  temperature: 28, humidity: 65\n}`}</pre></Card></div></>; }

function Recommendations() { return <><div className="recommendation-hero"><div className="hero-leaf"><CheckCircle2 size={28}/></div><div><span className="overline">GENERAL ADVISORY</span><h2>Small, explainable steps</h2><p>Recommendations combine the current soil condition, prototype crop score, and demonstration disease result.</p></div></div><div className="rec-grid"><Card><div className="rec-card-icon green"><Sprout size={20}/></div><span className="overline">CROP RECOMMENDATION</span><h3>Groundnut shows good suitability</h3><p>Under the current prototype conditions, groundnut has the highest suitability score. Continue monitoring moisture and local crop performance.</p></Card><Card><div className="rec-card-icon amber"><Camera size={20}/></div><span className="overline">DISEASE ADVISORY</span><h3>Early Blight in the demonstration result</h3><p>Monitor affected leaves, remove severely affected material, improve air circulation, and avoid prolonged leaf wetness.</p></Card><Card><div className="rec-card-icon blue"><Droplets size={20}/></div><span className="overline">SOIL ADVISORY</span><h3>Keep readings calibrated</h3><p>Use actual dry/wet reference values for the FC-28 and suitable standard buffer solutions for the pH module.</p></Card></div><div className="disclaimer"><AlertTriangle size={18}/><div><b>Project limitation</b><span>This prototype is not a replacement for professional agricultural advice. Sensor accuracy depends on calibration, and disease detection is a demo unless a validated model is integrated.</span></div></div></>; }

function Settings({ mode, setMode, interval, setIntervalValue }: { mode: Mode; setMode: (m: Mode) => void; interval: number; setIntervalValue: (n: number) => void }) { return <Card className="settings-card"><SectionTitle title="Operating mode" subtitle="Choose the source of values shown throughout the application"/><div className="mode-options"><button className={mode === 'demo' ? 'selected' : ''} onClick={() => setMode('demo')}><span className="radio"/><div><b>Demo Mode</b><small>Use centralized prototype values for demonstrations</small></div><Badge mode="demo" small/></button><button className={mode === 'live' ? 'selected' : ''} onClick={() => setMode('live')}><span className="radio"/><div><b>Live Hardware Mode</b><small>Use only verified ESP32 telemetry; never fall back silently</small></div><Badge mode="live" small/></button></div><div className="settings-divider"/><SectionTitle title="System status"/><div className="system-status"><div><span>Backend API</span><b className="good-text"><span className="tiny-dot"/>Available</b></div><div><span>Hardware status</span><b className={mode === 'live' ? 'warn-text' : 'good-text'}><span className="tiny-dot"/>{mode === 'live' ? 'Unavailable' : 'Demo mode'}</b></div><div><span>Refresh interval</span><select value={interval} onChange={e => setIntervalValue(Number(e.target.value))}><option value={5}>5 seconds</option><option value={15}>15 seconds</option><option value={30}>30 seconds</option></select></div></div><div className="notice"><AlertTriangle size={16}/><span>Operating mode changes are saved in this browser only. This project intentionally includes no account, payment, or unrelated settings.</span></div></Card>; }

export default function App() { const [page, setPage] = useState<Page>('Dashboard'); const [mode, setMode] = useState<Mode>(() => (localStorage.getItem('crop-mode') as Mode) || 'demo'); const [interval, setIntervalValue] = useState(15); const [mobileOpen, setMobileOpen] = useState(false); const [liveReading, setLiveReading] = useState<Reading | null>(null); const reading = mode === 'live' ? (liveReading || { soilMoisture: 0, soilPH: 0, temperature: 0, humidity: 0 }) : demoReading;
  useEffect(() => { localStorage.setItem('crop-mode', mode); }, [mode]);
  useEffect(() => { if (mode !== 'live') return; const get = () => fetch('/api/hardware/latest').then(r => r.json()).then(d => d.reading && validateReading(d.reading) && setLiveReading(d.reading)).catch(() => undefined); get(); const id = window.setInterval(get, interval * 1000); return () => window.clearInterval(id); }, [mode, interval]);
  const copy = pageCopy[page];
  const body = useMemo(() => { if (page === 'Dashboard') return <Dashboard reading={reading} mode={mode} setPage={setPage}/>; if (page === 'Crop Advisory') return <Advisory reading={reading}/>; if (page === 'Disease Detection') return <Disease/>; if (page === 'Soil Analysis') return <Soil reading={reading}/>; if (page === 'Sensor Monitoring') return <Sensors mode={mode} reading={reading}/>; if (page === 'Recommendations') return <Recommendations/>; return <Settings mode={mode} setMode={setMode} interval={interval} setIntervalValue={setIntervalValue}/>; }, [page, mode, reading, interval]);
  return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><Leaf size={21}/></div><div><b>Smart Crop</b><span>Advisory System</span></div><button className="close-mobile" onClick={() => setMobileOpen(false)}><X size={18}/></button></div><div className="side-label">WORKSPACE</div><nav>{nav.map(item => <button className={page === item.label ? 'active' : ''} key={item.label} onClick={() => { setPage(item.label); setMobileOpen(false); }}><item.icon size={18}/><span>{item.label}</span>{page === item.label && <ChevronRight size={15} className="nav-arrow"/>}</button>)}</nav><div className="sidebar-bottom"><div className="hardware-mini"><Cpu size={17}/><div><b>Hardware bridge</b><span>{mode === 'live' ? 'Awaiting telemetry' : 'Demo mode active'}</span></div></div><span className="version">BCA · IoT prototype v1.0</span></div></aside><main className="main"><header className="topbar"><button className="menu-button" onClick={() => setMobileOpen(true)}><Menu size={21}/></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14}/><b>{page}</b></div><div className="top-actions"><Badge mode={mode}/><button className="icon-button" title="Refresh dashboard" onClick={() => window.location.reload()}><RefreshCw size={17}/></button></div></header><div className="content"><div className="page-heading"><div><span className="overline">{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.description}</p></div><div className="heading-status"><Activity size={16}/><span>{mode === 'demo' ? 'Demo values active' : liveReading ? 'Telemetry received' : 'Hardware unavailable'}</span></div></div>{mode === 'live' && !liveReading && <div className="global-alert"><AlertTriangle size={18}/><b>Hardware unavailable</b><span>Live Hardware mode is selected. No simulated values are being substituted.</span><button onClick={() => setMode('demo')}>Switch to Demo Mode</button></div>}{mode === 'demo' && <div className="demo-strip"><span className="dot"/>All readings on this page are <b>DEMO DATA</b>, not live sensor measurements.</div>}{body}</div><footer><span>Smart Crop Advisory System · Academic prototype</span><span>Calibration and professional validation are required for real-world use.</span></footer></main></div>; }
