import { useCallback, useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, AlertTriangle, BarChart3, Camera, CheckCircle2, ChevronRight, CircleSlash2, Cpu, Droplets, Gauge, Leaf, Menu, RefreshCw, Settings as SettingsIcon, Thermometer, Upload, Waves, X } from 'lucide-react';
import { Page, Reading, validateReading } from './data';
import FieldAnimation from './FieldAnimation';

type HardwareStatus = { available: boolean; status: string; lastUpdated: string | null };
type IconType = typeof Leaf;
const nav: { label: Page; icon: IconType }[] = [
  { label: 'Dashboard', icon: BarChart3 }, { label: 'Crop Advisory', icon: Leaf }, { label: 'Disease Detection', icon: Camera },
  { label: 'Soil Analysis', icon: Droplets }, { label: 'Sensor Monitoring', icon: Activity }, { label: 'Recommendations', icon: CheckCircle2 }, { label: 'Settings', icon: SettingsIcon },
];
const copy: Record<Page, { eyebrow: string; title: string; description: string }> = {
  Dashboard: { eyebrow: 'Overview', title: 'Live field intelligence', description: 'Only verified readings received through the backend are displayed here.' },
  'Crop Advisory': { eyebrow: 'Decision support', title: 'Crop suitability', description: 'Suitability is calculated only when all required real inputs are available.' },
  'Disease Detection': { eyebrow: 'ESP32-CAM pathway', title: 'Inspect a crop leaf', description: 'Upload a leaf image when a trained disease model is connected.' },
  'Soil Analysis': { eyebrow: 'Soil health', title: 'Read the soil data', description: 'Status information appears only for valid sensor readings.' },
  'Sensor Monitoring': { eyebrow: 'Hardware bridge', title: 'Monitor telemetry', description: 'See real readings, history, and the ESP32 connection pathway.' },
  Recommendations: { eyebrow: 'Action plan', title: 'Recommendations', description: 'Guidance is generated only when sufficient real information exists.' },
  Settings: { eyebrow: 'System controls', title: 'Connection settings', description: 'Minimal controls for the backend connection and refresh interval.' },
};
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section>; }
function SectionTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { return <div className="section-title"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>; }
function Empty({ title, children }: { title: string; children: React.ReactNode }) { return <div className="empty-state"><CircleSlash2 size={28}/><h3>{title}</h3><p>{children}</p></div>; }
function StatusBadge({ connected }: { connected: boolean }) { return <span className={`status-badge ${connected ? 'connected' : 'disconnected'}`}><span className="dot"/>{connected ? 'Connected' : 'Disconnected'}</span>; }
function Stat({ label, value, unit, icon: Icon, tone }: { label: string; value: string; unit?: string; icon: IconType; tone: string }) { return <Card className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={20}/></div><div className="stat-copy"><span>{label}</span><strong>{value}{unit && <em>{unit}</em>}</strong></div></Card>; }
function SensorCards({ reading }: { reading: Reading | null }) { const items: [string, string, string | undefined, IconType, string][] = [['Soil Moisture', reading ? String(reading.soilMoisture) : 'No data available', reading ? '%' : undefined, Droplets, 'teal'], ['Soil pH', reading ? String(reading.soilPH) : 'No data available', undefined, Gauge, 'violet'], ['Temperature', reading ? String(reading.temperature) : 'No data available', reading ? '°C' : undefined, Thermometer, 'orange'], ['Humidity', reading ? String(reading.humidity) : 'No data available', reading ? '%' : undefined, Waves, 'blue']]; return <div className="stats-grid">{items.map(([label, value, unit, Icon, tone]) => <Stat key={label} label={label} value={value} unit={unit} icon={Icon} tone={tone}/>)}</div>; }
function TrendChart({ history }: { history: Reading[] }) { if (!history.length) return <Empty title="No historical data available">Connect the ESP32 and send telemetry to begin building real sensor history.</Empty>; return <div className="chart-wrap tall"><ResponsiveContainer width="100%" height={260}><LineChart data={history.map((r, i) => ({ ...r, time: r.timestamp ? new Date(r.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : `Reading ${i + 1}` }))}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e7eee9"/><XAxis dataKey="time" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip/><Line type="monotone" dataKey="soilMoisture" stroke="#218b67" strokeWidth={2} dot={false} name="Moisture %"/><Line type="monotone" dataKey="temperature" stroke="#d98942" strokeWidth={2} dot={false} name="Temperature °C"/><Line type="monotone" dataKey="humidity" stroke="#4b83bd" strokeWidth={2} dot={false} name="Humidity %"/><Line type="monotone" dataKey="soilPH" stroke="#8063ba" strokeWidth={2} dot={false} name="pH"/></LineChart></ResponsiveContainer></div>; }
function Dashboard({ reading, history, hardware, setPage }: { reading: Reading | null; history: Reading[]; hardware: HardwareStatus; setPage: (p: Page) => void }) { return <><div className="hero-grid"><Card className="welcome"><div className="hero-leaf"><Leaf size={28}/></div><div><span className="overline">HARDWARE STATUS</span><h2>{hardware.available ? 'ESP32 is connected' : 'No hardware data available'}</h2><p>{hardware.available ? 'The latest validated telemetry is shown below.' : 'Connect the ESP32 to begin receiving real sensor readings.'}</p><button className="button primary" onClick={() => setPage('Sensor Monitoring')}>Open sensor monitor <ChevronRight size={16}/></button></div></Card><Card className="connection-card"><div className="connection-top"><div><span className="overline">BACKEND API</span><h3>Telemetry service</h3></div><StatusBadge connected={hardware.available}/></div><Cpu size={38}/><p>{hardware.available ? 'Receiving verified JSON telemetry.' : 'Waiting for verified telemetry.'}</p>{hardware.lastUpdated && <small>Last updated {new Date(hardware.lastUpdated).toLocaleString()}</small>}</Card></div><SensorCards reading={reading}/><div className="two-col"><Card><SectionTitle title="Sensor trends" subtitle="Actual telemetry history from the backend" action={<button className="text-button" onClick={() => setPage('Sensor Monitoring')}>Open monitor <ChevronRight size={15}/></button>}/><TrendChart history={history}/></Card><Card><SectionTitle title="Crop suitability" subtitle="Calculated only from sufficient real inputs"/><Empty title="Insufficient data for crop suitability analysis.">Rainfall is not connected to a real source, so no crop percentage is calculated.</Empty></Card></div><Card><SectionTitle title="Hardware status"/><div className="hardware-status-grid"><div><b>ESP32</b><StatusBadge connected={hardware.available}/></div><div><b>ESP32-CAM</b><StatusBadge connected={false}/></div><div><b>Backend API</b><StatusBadge connected={true}/></div></div></Card></>; }
function Advisory({ reading }: { reading: Reading | null }) { return <Card><SectionTitle title="Prototype crop scoring" subtitle="Uses pH, moisture, temperature, humidity, and actual rainfall when available."/><div className="weight-list"><span>Soil pH <b>30%</b></span><span>Soil moisture <b>25%</b></span><span>Temperature <b>20%</b></span><span>Humidity <b>10%</b></span><span>Rainfall <b>15%</b></span></div><div className="advisory-empty"><Empty title="Insufficient data for crop suitability analysis.">{reading ? 'A real rainfall source is still required before a score can be calculated.' : 'Connect the ESP32 to provide the required real sensor inputs.'}</Empty></div></Card>; }
function Disease() { const [image, setImage] = useState<string | null>(null); return <div className="two-col"><Card><SectionTitle title="Upload Crop Leaf Image" subtitle="User upload and future ESP32-CAM integration"/><label className="upload-box">{image ? <img src={image} alt="Uploaded crop leaf preview"/> : <><div className="upload-icon"><Upload size={22}/></div><b>Choose a crop leaf image</b><span>PNG, JPG, or WEBP</span></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => { const file = e.target.files?.[0]; if (file) setImage(URL.createObjectURL(file)); }}/></label></Card><Card><SectionTitle title="Detection result" subtitle="Results appear only after actual image processing"/><Empty title="Disease detection model not configured.">The interface is ready for a trained model, but no disease has been detected or assigned.</Empty></Card><Card className="path-card"><SectionTitle title="ESP32-CAM status"/><div className="hardware-alert danger"><AlertTriangle size={18}/><div><b>ESP32-CAM disconnected</b><span>Connect the camera integration before expecting an image from hardware.</span></div></div></Card></div>; }
function Soil({ reading, history }: { reading: Reading | null; history: Reading[] }) { if (!reading) return <Card><Empty title="Sensor data unavailable.">Connect the ESP32 to display soil moisture, soil pH, temperature, and humidity.</Empty></Card>; return <><SensorCards reading={reading}/><Card><SectionTitle title="Current sensor conditions" subtitle="Status indicators for the latest valid reading"/><div className="condition-table"><div><span>Soil moisture</span><b>{reading.soilMoisture}%</b><em className="good-text">Valid reading</em></div><div><span>Soil pH</span><b>{reading.soilPH}</b><em className="good-text">Valid reading</em></div><div><span>Last updated</span><b>{reading.timestamp ? new Date(reading.timestamp).toLocaleTimeString() : 'No data available'}</b><em className="good-text">Backend time</em></div></div></Card><Card><SectionTitle title="Historical readings"/><TrendChart history={history}/></Card></>; }
function Sensors({ reading, history, hardware }: { reading: Reading | null; history: Reading[]; hardware: HardwareStatus }) { return <><Card><div className="sensor-head"><SectionTitle title="Live telemetry" subtitle="Only values received from the backend are displayed"/><StatusBadge connected={hardware.available}/></div><SensorCards reading={reading}/><div className={`hardware-alert ${hardware.available ? '' : 'danger'}`}>{hardware.available ? <CheckCircle2 size={18}/> : <AlertTriangle size={18}/>}<div><b>{hardware.available ? 'Telemetry available' : 'ESP32 disconnected'}</b><span>{hardware.available ? `Last updated ${hardware.lastUpdated ? new Date(hardware.lastUpdated).toLocaleString() : 'unknown'}.` : 'No sensor data available. Connect the ESP32 to begin receiving readings.'}</span></div></div></Card><Card><SectionTitle title="Sensor trends" subtitle="Actual historical telemetry only"/><TrendChart history={history}/></Card><div className="two-col"><Card><SectionTitle title="Hardware status"/><div className="hardware-status-grid vertical"><div><b>ESP32</b><StatusBadge connected={hardware.available}/></div><div><b>ESP32-CAM</b><StatusBadge connected={false}/></div><div><b>Backend API</b><StatusBadge connected={true}/></div></div></Card><Card><SectionTitle title="Wiring & pinout" subtitle="Verify pH output voltage against the ESP32 ADC-safe range."/><div className="pinout"><div><b>FC-28 A0</b><span>→ ESP32 GPIO 34</span></div><div><b>Soil pH</b><span>→ ESP32 GPIO 35</span></div><div><b>DHT11 DATA</b><span>→ ESP32 GPIO 4</span></div></div><pre>{`// Replace placeholders before uploading\nconst char* WIFI_NAME = "YOUR_WIFI_NAME";\nconst char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";\nconst char* SERVER_URL = "YOUR_SERVER_URL";\n\n// POST validated JSON telemetry to\n/api/hardware/telemetry`}</pre></Card></div></>; }
function Recommendations({ reading }: { reading: Reading | null }) { return <Card><SectionTitle title="Recommendations" subtitle="Generated only from sufficient real information"/><Empty title="Insufficient data to generate recommendation.">{reading ? 'Crop scoring needs a real rainfall source, and no disease model result is available.' : 'Connect the ESP32 and configure a disease model before generating recommendations.'}</Empty></Card>; }
function Settings({ hardware, interval, setIntervalValue }: { hardware: HardwareStatus; interval: number; setIntervalValue: (n: number) => void }) { return <Card className="settings-card"><SectionTitle title="Backend/API URL" subtitle="Current browser origin"/><div className="api-url">{window.location.origin}/api</div><div className="settings-divider"/><SectionTitle title="Hardware connection status"/><div className="system-status"><div><span>ESP32</span><b className={hardware.available ? 'good-text' : 'warn-text'}><span className="tiny-dot"/>{hardware.available ? 'Connected' : 'Disconnected'}</b></div><div><span>ESP32-CAM</span><b className="warn-text"><span className="tiny-dot"/>Disconnected</b></div><div><span>Refresh interval</span><select value={interval} onChange={e => setIntervalValue(Number(e.target.value))}><option value={5}>5 seconds</option><option value={15}>15 seconds</option><option value={30}>30 seconds</option></select></div></div><div className="notice"><AlertTriangle size={16}/><span>No demo mode or placeholder values are used. Hardware status is based on the backend response.</span></div></Card>; }
export default function App() { const [page, setPage] = useState<Page>('Dashboard'); const [reading, setReading] = useState<Reading | null>(null); const [history, setHistory] = useState<Reading[]>([]); const [hardware, setHardware] = useState<HardwareStatus>({ available: false, status: 'Disconnected', lastUpdated: null }); const [interval, setIntervalValue] = useState(15); const [mobileOpen, setMobileOpen] = useState(false);
  const refresh = useCallback(async () => { try { const [latestRes, historyRes, statusRes] = await Promise.all([fetch('/api/hardware/latest'), fetch('/api/hardware/history'), fetch('/api/hardware/status')]); const latest = await latestRes.json(); const old = await historyRes.json(); const status = await statusRes.json(); setReading(latest.reading && validateReading(latest.reading) ? latest.reading : null); setHistory(Array.isArray(old.readings) ? old.readings.filter(validateReading) : []); setHardware(status); } catch { setReading(null); setHistory([]); setHardware({ available: false, status: 'Backend unavailable', lastUpdated: null }); } }, []);
  useEffect(() => { refresh(); const id = window.setInterval(refresh, interval * 1000); return () => window.clearInterval(id); }, [refresh, interval]);
  const body = useMemo(() => { if (page === 'Dashboard') return <><FieldAnimation/><div className="dashboard-content"><Dashboard reading={reading} history={history} hardware={hardware} setPage={setPage}/></div></>; if (page === 'Crop Advisory') return <Advisory reading={reading}/>; if (page === 'Disease Detection') return <Disease/>; if (page === 'Soil Analysis') return <Soil reading={reading} history={history}/>; if (page === 'Sensor Monitoring') return <Sensors reading={reading} history={history} hardware={hardware}/>; if (page === 'Recommendations') return <Recommendations reading={reading}/>; return <Settings hardware={hardware} interval={interval} setIntervalValue={setIntervalValue}/>; }, [page, reading, history, hardware, interval]);
  const heading = copy[page]; return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><Leaf size={21}/></div><div><b>Smart Crop</b><span>Advisory System</span></div><button className="close-mobile" onClick={() => setMobileOpen(false)}><X size={18}/></button></div><div className="side-label">WORKSPACE</div><nav>{nav.map(item => <button className={page === item.label ? 'active' : ''} key={item.label} onClick={() => { setPage(item.label); setMobileOpen(false); }}><item.icon size={18}/><span>{item.label}</span>{page === item.label && <ChevronRight size={15} className="nav-arrow"/>}</button>)}</nav><div className="sidebar-bottom"><div className="hardware-mini"><Cpu size={17}/><div><b>Hardware bridge</b><span>{hardware.available ? 'Telemetry connected' : 'No hardware data'}</span></div></div><span className="version">BCA · IoT prototype v1.0</span></div></aside><main className="main"><header className="topbar"><button className="menu-button" onClick={() => setMobileOpen(true)}><Menu size={21}/></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14}/><b>{page}</b></div><div className="top-actions"><StatusBadge connected={hardware.available}/><button className="icon-button" title="Refresh" onClick={refresh}><RefreshCw size={17}/></button></div></header><div className="content"><div className="page-heading"><div><span className="overline">{heading.eyebrow}</span><h1>{heading.title}</h1><p>{heading.description}</p></div><div className="heading-status"><Activity size={16}/><span>{hardware.available ? 'Verified telemetry available' : 'No hardware data available'}</span></div></div>{!hardware.available && <div className="global-alert"><AlertTriangle size={18}/><b>No hardware data available</b><span>Connect the ESP32 to begin receiving readings. No placeholder values are being shown.</span></div>}{body}</div><footer><span>Smart Crop Advisory System · Academic IoT project</span><span>Only validated hardware data is displayed.</span></footer></main></div>; }
